version: '3.8'
services:

  app:
    image: kosbalint/be-feladatsor:v0.0.21
    container_name: be_feladatsor
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - postgres
    env_file:
      - stack.env

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=be-febe
    volumes:
      - /nfs/feladatbekuldo-be:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db
