version: '3.8'
services:

  app:
    image: gcr.io/feladatsor-15604/feladatsor-backend:v0.0.18
    container_name: be_feladatsor
    restart: unless-stopped
    ports:
      - 8080:8080

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=be-febe
    volumes:
      - /nfs/feladatbekuldo-be:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db
