name: Build and push Docker image to ECR

on:
  push:
    tags:
      - v*

jobs:
  push-image:
    runs-on: ubuntu-latest
    name: Build and push ${{ github.repository }} to GitLab repository
    steps:
      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: gcr.io/feladatsor-15604/${{ github.event.repository.name }}
          flavor: |
            latest=false

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          #registry: gcr.io
          context: .
          platforms: linux/x86_64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
