name: Build and push Docker image to ECR

on:
  push:
    tags:
      - v*

jobs:
  push-image:
    runs-on: ubuntu-latest
    name: Build and push ${{ github.repository }} to DockerHub repository
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: kosbalint/be-feladatsor
          flavor: |
            latest=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            "GENERATE_SOURCEMAP=false"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
